import type { Metadata } from 'next'

import "../../public/siux/assets/css/siux.main.css"
import "../../public/siux/assets/css/siux.main.responsive.css"
import "../../public/siux/assets/css/siux.icon.remixicon.css"
import "../../public/siux/assets/css/siux.extend.css"

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SIUX Studio + Next.js Integration',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body className="padding-left-s padding-right-s container-desktop">{children}</body>
    </html>
  )
}